defmodule Core.Repo.Migrations.CreateUser do
  use Ecto.Migration

  def change do
    create table(:snitch_users) do
      add :first_name, :string # Just a name perhaps?
      add :last_name, :string
      add :email, :string
      add :password_hash, :string, comment: "Generated by argon2_elixir:hash_pwd_salt with default 16 byte salt length."
      add :is_admin?, :boolean, default: false

      add :sign_in_count, :integer, default: 0
      add :failed_attempts, :integer, default: 0

      # add :snitch_api_key, :string
      # add :remember_token, :string

      # add :persistence_token, :string
      # add :reset_password_token, :string
      # add :perishable_token, :string
      # add :authentication_token, :string
      # add :unlock_token, :string
      # add :confirmation_token, :string

      # add :last_request_at, :string
      # add :current_sign_in_at, :string
      # add :last_sign_in_at, :string

      # add :current_sign_in_ip, :string
      # add :last_sign_in_ip, :string

      # add :login, :string

      # add :locked_at, :string

      # add :reset_password_sent_at, :naive_datetime
      # add :remember_created_at, :naive_datetime
      # add :deleted_at, :naive_datetime
      # add :confirmed_at, :naive_datetime
      # add :confirmation_sent_at, :naive_datetime
      timestamps()
    end

    create unique_index(:snitch_users, [:email])
  end
end
